### ISSUE TITLE
line 248 on blocks.js is crashing because mcData.blocksByName.spawner is undefined

### ISSUE THREAD

**Issue by 40ea57d3ee3c07bf1c102b466e1c3091** [7GrandDadPGN/MinibloxTranslationLayer#10]
### Preflight Checklist

- [X] I am not a pest
- [X] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### What OS(es) are you using?

Other Linux

### Operating System Version

Linux stupid 6.11.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000 x86_64 GNU/Linux

### What architecture are you using?

x64

### Last Known Working Miniblox Translation Layer commit

d280648

### Expected Behavior

It to..... work

### Actual Behavior

Crashes because of line 248 because id is undefined because spawner is undefined

### Additional Information

its like 4am for me bare with me :pray:

**Comment by 7GrandDadPGN** [comment]
Sorry, fixed.
