### ISSUE TITLE
io server disconnected 

### ISSUE THREAD

**Issue by iceswallowpis** [7GrandDadPGN/MinibloxTranslationLayer#11]
### Preflight Checklist

- [X] I am not a pest
- [X] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### What OS(es) are you using?

Windows

### Operating System Version

windows 11 23h2 22631.4317

### What architecture are you using?

x64

### Last Known Working Miniblox Translation Layer commit

idk

### Expected Behavior

idk let me connect and do gaming 

### Actual Behavior

![image](https://github.com/user-attachments/assets/2053aee0-8f5e-4b03-99e4-de2fd70f90e3)
![image](https://github.com/user-attachments/assets/38b1b8a4-0901-451f-afee-1353d46162f4)
![image](https://github.com/user-attachments/assets/681ca1a5-c185-4076-a4e7-9861c503948e)

### Additional Information

it was working fine yesterday on the current commit version no matter which version i use it gives me this error, i tried redownloading nodejs, the translation layer, different clients and vanilla nothing has worked and my antivirus is off and i have nodejs added to the firewall exceptions

**Comment by 7GrandDadPGN** [comment]
Fixed

**Comment by DataM0del** [comment]
Yeah, vector is very smart and won't fix his AntiCheat, but rather he will remove the CAPTCHAs again (which I predicted lol) and rename a packet (which is a new thing lol, he renamed `CPacketEntityRelPositionAndRotation` to `CPacketEntityRelativePositionAndRotation`)
