### ISSUE TITLE
Team is not assigned(?)

### ISSUE THREAD

**Issue by 40ea57d3ee3c07bf1c102b466e1c3091** [7GrandDadPGN/MinibloxTranslationLayer#12]
### Preflight Checklist

- [X] I am not a pest
- [X] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### What OS(es) are you using?

Other Linux

### Operating System Version

Linux stupid 6.11.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000 x86_64 GNU/Linux

### What architecture are you using?

x64

### Last Known Working Miniblox Translation Layer commit

1b5127c

### Expected Behavior

Killaura will ignore my teammate and go for other players.

### Actual Behavior

Killaura will think my teammate is not on my team

### Additional Information

guessin its a team issue

**Comment by 40ea57d3ee3c07bf1c102b466e1c3091** [comment]
nevermind, it seems like a one-off.

**Comment by DataM0del** [comment]
I use LiquidBounce Legacy with color set as the teams mode. Not sure if it still works because vector patched my funny VPN bypass that used the discord activity socket.IO URL instead of the main socket.IO URL, it worked for **3 hours**...

**Comment by DataM0del** [comment]
If you're wondering why there isn't an announcement about the bypass or anything, here's why...
![image](https://github.com/user-attachments/assets/c6042c24-685f-463f-831d-76a1dc42184a)
And he never really responded so...
![image](https://github.com/user-attachments/assets/8ae44f82-2930-4a5e-a911-aa21a17b65cf)

**Comment by 7GrandDadPGN** [comment]
I'm rewriting the tablist handler right now, but any teamcheck that uses the first colorcode in the name should work fine.
