### ISSUE TITLE
Cant use on termux

### ISSUE THREAD

**Issue by vantthinkofanameyet** [7GrandDadPGN/MinibloxTranslationLayer#13]
### Preflight Checklist

- [X] I am not a pest
- [X] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### What OS(es) are you using?

Other Linux

### Operating System Version

Android (14, 64-bit)

### What architecture are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The packages would install properly and the server would run

### Actual Behavior

The packages fail to install and the server cant be run
![Screenshot_20241110_111511_ZArchiver](https://github.com/user-attachments/assets/5ab4f378-fda1-4f02-9ec7-6e87290a160d)
![Screenshot_20241110_111413_Termux](https://github.com/user-attachments/assets/59ccce16-98fb-4d84-96ed-1cf53e441fb2)
![Screenshot_20241110_111357_Termux](https://github.com/user-attachments/assets/927c3792-340a-4d35-b571-e24e4c5f9d94)

**Comment by DataM0del** [comment]
> ### Preflight Checklist
> 
>     * [x]  I am not a pest
> 
>     * [x]  I am using the latest version of Miniblox Translation Layer (`git pull`)
> 
>     * [x]  My Minecraft client is running on 1.8.9 (you can use ViaVersion)
> 
>     * [x]  I have searched the issues of this repository and believe that this is not a duplicate
> 
> 
> ### What OS(es) are you using?
> 
> Other Linux
> ### Operating System Version
> 
> Android (14, 64-bit)
> ### What architecture are you using?
> 
> arm64 (including Apple Silicon)
> ### Last Known Working Miniblox Translation Layer commit
> 
> _No response_
> ### Expected Behavior
> 
> The packages would install properly and the server would run
> ### Actual Behavior
> 
> The packages fail to install and the server cant be run ![Screenshot_20241110_111511_ZArchiver](https://private-user-images.githubusercontent.com/187011531/384678911-5ab4f378-fda1-4f02-9ec7-6e87290a160d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzc3NDEsIm5iZiI6MTczMTI3NzQ0MSwicGF0aCI6Ii8xODcwMTE1MzEvMzg0Njc4OTExLTVhYjRmMzc4LWZkYTEtNGYwMi05ZWM3LTZlODcyOTBhMTYwZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQyMjI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGY2OTFkYTBiYzBkMDlhZTAzMTUwOWM1N2JkNTMyYWY2NWNiMDE0NDdlZWY2NjYzYmY4YzRiOTliOTNjMWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1g-PZMB3eN219GK-iLgUYcaoDWWKeDGBxZ4f49LXbEU) ![Screenshot_20241110_111413_Termux](https://private-user-images.githubusercontent.com/187011531/384678913-59ccce16-98fb-4d84-96ed-1cf53e441fb2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzc3NDEsIm5iZiI6MTczMTI3NzQ0MSwicGF0aCI6Ii8xODcwMTE1MzEvMzg0Njc4OTEzLTU5Y2NjZTE2LTk4ZmItNGQ4NC05NmVkLTFjZjUzZTQ0MWZiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQyMjI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGU5ODMxMmRiYTA4YTA1YWExYTBlNTIwMTQ3ZGViYTY4Zjc0OTgzYzcxMzY5ZjQ2MjA1M2I0MzIzYzg0YjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RwGuoeHRLNCTXdWupr-TCSQ-Xoqb3OBcQfN2eO4jCek) ![Screenshot_20241110_111357_Termux](https://private-user-images.githubusercontent.com/187011531/384678923-927c3792-340a-4d35-b571-e24e4c5f9d94.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzc3NDEsIm5iZiI6MTczMTI3NzQ0MSwicGF0aCI6Ii8xODcwMTE1MzEvMzg0Njc4OTIzLTkyN2MzNzkyLTM0MGEtNGQzNS1iNTcxLWUyNGU0YzVmOWQ5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQyMjI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2Q1MTg5YjUxYWM2ZGQ1N2E1OWRkMTg2YTdjZWU2NzEwMjMzOTBmOWFmN2NkZjRkMGIyZDdlZjI3MWVmMDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n3XjiinvVpGFddpyihA-A-AWc-_XHupjc_2uMgDDHxE)
> ### Additional Information
> 
> _No response_

This isn't really a supported OS, but maybe I'll dig into it, I do have a Android 10 phone with Termux :)

**Comment by DataM0del** [comment]
@vantthinkofanameyet I think this is because you haven't rooted your phone and Termux can't access anything outside of its data directory if your phone isn't rooted.
You can just `git clone` the repository in the Termux data directory, or you can root your phone, run `su` to try and ask your root app for root.
Note that your warranty (mine is already off warranty anyways but I just don't really want to wipe my phone) might be voided because we live in a dystopian world you can't install a different OS on a phone without voiding your warranty, but on PC there is no voiding of warranty, and you don't have to go through 500 steps.

**Comment by DataM0del** [comment]
@vantthinkofanameyet It seems like it's working? I just cloned it into `~/source` (which is inside the data directory of Termux) and it installed the dependencies and seems to be working, I haven't tested it as I don't have Minecraft (not the Bedcock edition, that also isn't installed either though) installed on my phone.
The punycode deprecation warning shouldn't affect anything, it's probably some dependency's fault, so it doesn't matter.

**Comment by DataM0del** [comment]
@vantthinkofanameyet I tested it, it works, please close the issue as completed.

**Comment by vantthinkofanameyet** [comment]
seems like using git clone instead of downloading the repo fixed it, thanks anyway!
