### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by DataM0del** [7GrandDadPGN/MinibloxTranslationLayer#15]
### Preflight Checklist

- [X] I am not a pest
- [X] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### Problem Description

So, you want to stream? So, you also want to play Miniblox. Oops, you got IP banned by Mr. What's Your Email in 2024 (Tester :point_left:)! Well... What now?
Usually, you'd connect to a VPN or etc. But your stream is now laggy and has 5 second delays, and even worse, everyone's complaining about it!
So, you set up a split tunneling system, Node.JS goes through the VPN, other requests bypass the VPN and go directly to the server.
But, what about the people *not* able to do that?
Proton VPN users (including me) can't use split tunneling unless they pay money, and that's a client side restriction! (I wouldn't use it anyways).
Also, what if your VPN is completely detected,
but you have a proxy server that isn't (e.g. one you stole from Urban VPN using, self-promo alert, my [Urban VPN server details script](https://codeberg.org/RealPacket/UrbanVPNServerDetails), which was meant for connecting to `hylex.gg` because Proton VPN only allows you use servers in NL, US, or JP, and that's only on Linux; everything everything else doesn't let you even PICK A SERVER, you have to either change servers on Android (but that has a cooldown, you could just disconnect and reconnect until you get the server you want), or just constantly disconnect and reconnect until you get the server)?

### Proposed Solution

Add proxy support.

### Alternatives Considered

- Buying a VPN (don't have enough :dollar: for that, my current balance is $0.00, aka cheapskate)
- Using a built-in proxy manager in a Minecraft client (doesn't work, you're connecting to localhost, and the Node.JS script sends the requests, not the client)
- Switching back to Windows to use SoftEther VPN with the VPNGate plugin to add public servers (no, I hate Windows, I will stay on Linux forever, not even my job would force me on Windows)

### Additional Information

You can use the `proxy-agent` library or similar ones.
Anyways, it's 11 PM EST (I'm in Georgia right now), so I can't keep writing and I need to go to bed.
I'll try to implement this too.

**Comment by 7GrandDadPGN** [comment]
Not planned.
