### ISSUE TITLE
some stuff dont work

### ISSUE THREAD

**Issue by Betabeta** [7GrandDadPGN/MinibloxTranslationLayer#16]
### Preflight Checklist

- [X] I am not a pest
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate
- [ ] I am using the latest version of Miniblox Translation Layer (`git pull`)

### What OS(es) are you using?

Other Linux

### Operating System Version

Linux penguin 6.6.50-05090-g02ec56928355 #1 SMP PREEMPT_DYNAMIC Fri, 8 Nov 2024 00:13:13 +0000 x86_64 GNU/Linux

### What architecture are you using?

x64

### Expected Behavior

to be able to open doors,trapdoors and to be able to craft in survival

### Actual Behavior

doors,trapdoors auto close crafting doesnt work

**Comment by Betabeta** [comment]
how do you even use git pull

**Comment by DataM0del** [comment]
you run it in your terminal, it pulls the latest changes.

**Comment by 7GrandDadPGN** [comment]
Not planned, crafting is wildly different between the two games, and I can't be asked to support it.
