### ISSUE TITLE
knockback doesnt work

### ISSUE THREAD

**Issue by Betabeta** [7GrandDadPGN/MinibloxTranslationLayer#17]
### Preflight Checklist

- [X] I am not a pest
- [ ] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### What OS(es) are you using?

Other Linux

### Operating System Version

Linux penguin 6.6.50-05090-g02ec56928355 #1 SMP PREEMPT_DYNAMIC Fri, 8 Nov 2024 00:13:13 +0000 x86_64 GNU/Linux

### What architecture are you using?

x64

### Expected Behavior

title speaks for itself

### Actual Behavior

title

**Comment by 7GrandDadPGN** [comment]
Fixed, thanks for reporting!
