### ISSUE TITLE
add custom world support

### ISSUE THREAD

**Issue by ILikeCodingg5565** [7GrandDadPGN/MinibloxTranslationLayer#18]
### Preflight Checklist

- [X] I am not a pest
- [X] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### Problem Description

Add support for custom worlds. Maybe u can "port" or translate to it using a custom command 
so for example, you run a custom script on miniblox, this assigns each custom world a different and unique tag. ingame, you type something like /cjoin <tag>

### Proposed Solution

above

### Alternatives Considered

idk this is a suggestion :3

### Additional Information

:3

**Comment by 7GrandDadPGN** [comment]
You can do /join (gameid) to join any server specified, basically open the game in the browser, join the custom world, then open the devconsole to find the gameid, then do /join, enjoy!
