### ISSUE TITLE
impossible to open node js/npm.ps1 using terminal

### ISSUE THREAD

**Issue by Zemper123** [7GrandDadPGN/MinibloxTranslationLayer#20]
### Preflight Checklist

- [X] I am not a pest
- [X] I am using the latest version of Miniblox Translation Layer (`git pull`)
- [X] My Minecraft client is running on 1.8.9 (you can use ViaVersion)
- [X] I have searched the issues of this repository and believe that this is not a duplicate

### What OS(es) are you using?

Windows

### Operating System Version

Windows 10 pro

### What architecture are you using?

x64

### Expected Behavior

npm install will work and then i will run node index.js

### Actual Behavior

![Screenshot_447](https://github.com/user-attachments/assets/48c40b54-fdec-4578-bfa5-be0cb453146b)
i see a error and i redownloaded the node js. and try redownload miniblox traslation layer but error still here

### Additional Information

i run ONLY npm install and nothing else.i try reading file README but still doesnt work.
this is what error say:
npm:impossible to load file C:\Program Files\nodejs\npm.ps1,because the execution of scripts about
is disabled in this system. For more information look about_Execution_Policies.
stoke:1 sign:1
+ npm install
+ ~~~

**Comment by DataM0del** [comment]
Windows moment, you need to set your execution policy.

**Comment by DataM0del** [comment]
```ps1
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser
```
feel free to adjust the scope.

**Comment by Zemper123** [comment]
I found a fix
