### ISSUE TITLE
Official server :fire:

### ISSUE THREAD

**Issue by DataM0del** [7GrandDadPGN/MinibloxTranslationLayer#6]
Yes, you can self-host it... However, it would be cool...
Would have to manage VPSes and stuff, would need residential proxies / VPNs.

**Comment by aauth** [comment]
wouldn't this create unnecessary latency

**Comment by DataM0del** [comment]
Yes but lazy people can just connect to the official server, and because you can self host it, people can just run their own public miniblox translation layer instance or just use it for themselves!

**Comment by qwertyui-is-back** [comment]
seems cool

**Comment by ForgedSengoku** [comment]
rat

**Comment by DataM0del** [comment]
> rat

a VPS would run the translation layer, not your PC, therefore, it wouldn't be a RAT, as there's no reason to rat a VPS when you can just SSH into it anyways.

**Comment by joeengo** [comment]
wouldn't this be a pain to do, you would need a new proxy for each user and what happens if one just gets ip banned? we need another, not a very plausible idea.

**Comment by joeengo** [comment]
> wouldn't this be a pain to do, you would need a new proxy for each user and what happens if one just gets ip banned? we need another, not a very plausible idea.

*you would need a new proxy for each user for a good experience.

**Comment by DataM0del** [comment]
Yes, it'd be hard, but the outcome for this would be nice.
